# Generated by Django 4.0.2 on 2022-02-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(max_length=20, verbose_name='URLs'),
        ),
    ]
