# Generated by Django 4.0.2 on 2022-02-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0004_urlvisitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='URLVisitCount',
        ),
    ]
