# Generated by Django 4.0.2 on 2022-02-02 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0005_shortener_count_delete_urlvisitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='count',
        ),
    ]
